# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")

Cocktail.create(name: "El Amentador", image: "https://images.unsplash.com/photo-1514361892635-6b07e31e75f9?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=1babec6c62cca17f98a64f8785d3efba&auto=format&fit=crop&w=1050&q=80")
Cocktail.create(name: "El Bombonero", image: "https://images.unsplash.com/photo-1470338745628-171cf53de3a8?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=b021b2cbe86640f8b50c8b24bc03b576&auto=format&fit=crop&w=634&q=80")
Cocktail.create(name: "La Brescia", image: "https://images.unsplash.com/photo-1517644493876-7864565e3bf9?ixlib=rb-0.3.5&s=4d17e8794a83555fe98ae7f1a28e3bde&auto=format&fit=crop&w=634&q=80")
Cocktail.create(name: "La Lemontada", image: "https://images.unsplash.com/photo-1531387367216-681093c0279b?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=73ca72de11ae9cd2fa7367dc1ee76705&auto=format&fit=crop&w=1316&q=80")
Cocktail.create(name: "El Figuiso", image: "https://images.unsplash.com/photo-1514361726087-38371321b5cd?ixlib=rb-0.3.5&s=187854b8055667391ffae62b28659251&auto=format&fit=crop&w=1350&q=80")
Cocktail.create(name: "La Tramontane", image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=6b1d319c9d079085df12025ac37e9e1e&auto=format&fit=crop&w=1350&q=80")

Dose.create(description: "Tons of", cocktail_id: 24 , ingredient_id: 2)
Dose.create(description: "5cl", cocktail_id: 24 , ingredient_id: 7)
Dose.create(description: "5cl", cocktail_id: 24 , ingredient_id: 8)
Dose.create(description: "5cl", cocktail_id: 24 , ingredient_id: 10)

Dose.create(description: "Tons of", cocktail_id: 25 , ingredient_id: 2)
Dose.create(description: "5cl", cocktail_id: 25 , ingredient_id: 7)
Dose.create(description: "5cl", cocktail_id: 25 , ingredient_id: 8)
Dose.create(description: "5cl", cocktail_id: 25 , ingredient_id: 10)
Dose.create(description: "3cl", cocktail_id: 25 , ingredient_id: 15)
Dose.create(description: "1cl", cocktail_id: 25 , ingredient_id: 25)
Dose.create(description: "2.5cl", cocktail_id: 25 , ingredient_id: 36)
Dose.create(description: "1cl", cocktail_id: 25 , ingredient_id: 7)

Dose.create(description: "Tons of", cocktail_id: 26 , ingredient_id: 2)
Dose.create(description: "5cl", cocktail_id: 26 , ingredient_id: 9)
Dose.create(description: "1cl", cocktail_id: 26 , ingredient_id: 46)
Dose.create(description: "2.5cl", cocktail_id: 26 , ingredient_id: 3)
Dose.create(description: "1cl", cocktail_id: 26 , ingredient_id: 19)

Dose.create(description: "Tons of", cocktail_id: 27 , ingredient_id: 2)
Dose.create(description: "5cl", cocktail_id: 27 , ingredient_id: 9)
Dose.create(description: "1cl", cocktail_id: 27 , ingredient_id: 46)
Dose.create(description: "2.5cl", cocktail_id: 27 , ingredient_id: 3)
Dose.create(description: "1cl", cocktail_id: 27 , ingredient_id: 19)

Dose.create(description: "Tons of", cocktail_id: 28 , ingredient_id: 2)
Dose.create(description: "5cl", cocktail_id: 28 , ingredient_id: 9)
Dose.create(description: "1cl", cocktail_id: 28 , ingredient_id: 66)
Dose.create(description: "2.5cl", cocktail_id: 28 , ingredient_id: 9)
Dose.create(description: "1cl", cocktail_id: 28 , ingredient_id: 15)


Ingredient.create(name: "mint leaves")
Ingredient.create(name: "Cranberries")
Ingredient.create(name:"Johnnie Walker")
Ingredient.create(name:"Apple cider")
Ingredient.create(name:"Everclear")
Ingredient.create(name:"Cranberry juice")
Ingredient.create(name:"Egg yolk")
Ingredient.create(name:"Egg")
Ingredient.create(name:"Grape juice")
Ingredient.create(name:"Peach nectar")
Ingredient.create(name:"Lemon")
Ingredient.create(name:"Firewater")
Ingredient.create(name:"Lemonade")
Ingredient.create(name:"Lager")
Ingredient.create(name:"Whiskey")
Ingredient.create(name:"Absolut Citron")
Ingredient.create(name:"Pisco")
Ingredient.create(name:"Irish cream")
Ingredient.create(name:"Ale")
Ingredient.create(name:"Chocolate liqueur")
Ingredient.create(name:"Midori melon liqueur")
Ingredient.create(name:"Sambuca")
Ingredient.create(name:"Cider")
Ingredient.create(name:"Sprite")
Ingredient.create(name:"7-Up")
Ingredient.create(name:"Blackberry brandy")
Ingredient.create(name:"Peppermint schnapps")
Ingredient.create(name:"Creme de Cassis")
Ingredient.create(name:"Jack Daniels")
Ingredient.create(name:"Bailey's irish cream")
Ingredient.create(name:"151 proof rum")
Ingredient.create(name:"Absolut Vodka")
Ingredient.create(name:"Goldschlager")
Ingredient.create(name:"Crown Royal")
Ingredient.create(name:"Cointreau")
Ingredient.create(name:"Vermouth")
Ingredient.create(name:"Advocaat")
Ingredient.create(name:"Absolut Kurant")
Ingredient.create(name:"Beer")
Ingredient.create(name:"Kool-Aid")
Ingredient.create(name:"Cherry Heering")
Ingredient.create(name:"White Creme de Menthe")
Ingredient.create(name:"Malibu rum")
Ingredient.create(name:"Vanilla vodka")
Ingredient.create(name:"J\u00e4germeister")
Ingredient.create(name:"Kiwi liqueur")
Ingredient.create(name:"Grand Marnier")
Ingredient.create(name:"Cachaca")
Ingredient.create(name:"Peachtree schnapps")
Ingredient.create(name:"Wild Turkey")
Ingredient.create(name:"Cranberry vodka")
Ingredient.create(name:"Corona")
Ingredient.create(name:"Orange juice")
Ingredient.create(name:"Yukon Jack")

